name = "lapce-julia-ls"
version = "0.0.3"
author = "VarLad"
display-name = "Julia (LanguageServer.jl)"
description = "Julia plugin for the Lapce Editor - Powered by LanguageServer.jl"
wasm = "bin/lapce-julia.wasm"
icon = "juliadots-icon.png"

[activation]
language = ["julia"]
workspace-contains = ["*/Project.toml", "*/Manifest.toml"]

# [config."volt.serverArgs"]
# default = []
# description = ""

# [config."lspSettingArray"]
# default = []
# description = ""

# [config."lspSettingString"]
# default = ""
# description = ""

# [config."lspSettingBool"]
# default = false
# description = ""
