name = "lapce-julia-ls"
version = "0.0.3"
author = "VarLad"
display-name = "Julia (LanguageServer.jl)"
description = "Julia plugin for the Lapce Editor - Powered by LanguageServer.jl"
wasm = "bin/lapce-julia.wasm"
icon = "assets/juliadots-icon.png"
repository = "https://github.com/VarLad/lapce-julia"

[activation]
language = ["julia"]
workspace-contains = ["*/*.py"]

# [config."volt.serverArgs"]
# default = []
# description = ""

# [config."lspSettingArray"]
# default = []
# description = ""

# [config."lspSettingString"]
# default = ""
# description = ""

# [config."lspSettingBool"]
# default = false
# description = ""
